# Generated by Django 5.2.5 on 2025-09-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_totalbalance_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('deduction_date', models.DateField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='api.totalbalance')),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
