# Generated by Django 5.2.5 on 2025-09-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contributors_balance_deductionhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='contributions',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='api.contributors'),
        ),
    ]
