# Generated by Django 5.2.5 on 2025-09-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_contributions_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='date_required',
        ),
    ]
