# Generated by Django 5.2.5 on 2025-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_contributions_date_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='date_paid',
            field=models.DateField(auto_now_add=True),
        ),
    ]
